yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name="post_create"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='main')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/_footer.html
<footer class="footer-area footer--light">
    <div class="footer-big">
        <!-- start .container -->
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-12">
                    <div class="footer-widget">
                        <div class="widget-about">
                            <img src="https://via.placeholder.com/250x60?text=Yatube" alt="" class="img-fluid">
                            <p>Сайт о блогерстве</p>
                            <ul class="contact-details">
                                <li>
                                    <span class="icon-earphones"></span> Позвони нам:
                                    <a href="tel:344-755-111">xxx-xxx-xxx</a>
                                </li>
                                <li>
                                    <span class="icon-envelope-open"></span> Поддержка:
                                    <a href="mailto:alexmarksonit@gmail.com">alex@support.com</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- Ends: .footer-widget -->
                </div>
                <!-- end /.col-md-4 -->
                <div class="col-md-3 col-sm-4">
                    <div class="footer-widget">
                        <div class="footer-menu footer-menu--1">
                            <h4 class="footer-widget-title">Популярые категории</h4>
                            <ul>
                                <li>
                                    <a href="{% url 'main:index' %}">Все записи</a>
                                </li>
                                <li>
                                    <a href="{% url 'about:author' %}">Автор</a>
                                </li>
                                <li>
                                    <a href="{% url 'about:tech' %}">Техническая информация</a>
                                </li>
                                <li>
                                    <a href="{% url 'login' %}">Логин</a>
                                </li>
                            </ul>
                        </div>
                        <!-- end /.footer-menu -->
                    </div>
                    <!-- Ends: .footer-widget -->
                </div>
                <!-- end /.col-md-3 -->

                <div class="col-md-3 col-sm-4">
                    <div class="footer-widget">
                        <div class="footer-menu">
                            <h4 class="footer-widget-title">Другие пункты</h4>
                        </div>
                        <!-- end /.footer-menu -->
                    </div>
                    <!-- Ends: .footer-widget -->
                </div>
                <!-- end /.col-lg-3 -->

                <div class="col-md-3 col-sm-4">
                    <div class="footer-widget">
                        <div class="footer-menu no-padding">
                            <h4 class="footer-widget-title">Поддержи нас</h4>
                        </div>
                        <!-- end /.footer-menu -->
                    </div>
                    <!-- Ends: .footer-widget -->
                </div>
                <!-- Ends: .col-lg-3 -->

            </div>
            <!-- end /.row -->
        </div>
        <!-- end /.container -->
    </div>
    <!-- end /.footer-big -->

    <div class="mini-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright-text">
                        {% if user.is_authenticated %}
                            <p>© {{ year }}
                                <a href="{% url 'main:index' %}">Yatube</a>. Все права защищены. Создано
                                <a href="#">Дополнительно</a>
                            </p>
                        {% else %}
                            <p>
                                <a href="#">Alex M</a>. 
                            </p>
                        {% endif %}
                    </div>

                    <div class="go_top">
                        <span class="icon-arrow-up"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

yatube/templates/includes/_header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light pb-7">
    <a class="navbar-brand" href="{% url 'main:index' %}">Yatube</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:index' %}">Главная</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    О себе
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'about:tech' %}">Техническая информация</a>
                    <a class="dropdown-item" href="{% url 'about:author' %}">Автор</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Поиск..." aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Поиск</button>
        </form>
        {% if user.is_authenticated %}
            <div class="ml-2">
                <a href="{% url 'main:post_create' %}" class="btn btn-outline-primary my-2 my-sm-0" type="submit">Добавить пост</a>
            </div>
        {% else %}
            <div class="ml-2">
                <a class="btn btn-outline-primary my-2 my-sm-0" type="submit">Зайти</a>
            </div>
        {% endif %}
    </div>
</nav>