yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name="post_create"),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name="profile_unfollow"
    ),

]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='main')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок',
                             help_text='Дайте название группе')
    slug = models.SlugField(unique=True, verbose_name='Ярлык для URL',
                            help_text='Дайте уникальный url')
    description = models.TextField(verbose_name='Описание',
                                   help_text='Дайте детальное описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title[:15]


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Дайте детальное описание поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации',
                                    help_text='Указывается дата публикации',
                                    db_index=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор', related_name="posts",
                               help_text='Указывается автор поста')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              blank=True, null=True, related_name="posts",
                              verbose_name='Группа',
                              help_text='Указывается принадлежность к группе')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Добавить картинки к посту'
    )

    class Meta:
        ordering = ('-pub_date', )
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             verbose_name='Пост', related_name="comments",
                             help_text='Указывается поста к комментрию')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор комментария',
                               related_name="comments",
                               help_text='Указывается автор комментария')
    text = models.TextField(verbose_name='Комментарий',
                            help_text='Дайте комментарий')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата публикации',
                                   help_text='Указывается дата публикации')

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower',
                             verbose_name='Последователь',
                             help_text='Указывается автор комментария')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following',
                               verbose_name='За кем следят',
                               help_text='Указывается автор комментария')
    created = models.DateTimeField(auto_now_add=True)

yatube/posts/forms.py
from django import forms

from posts.models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Post, Group, User, Comment, Follow
from .utils import paginator_create


@cache_page(20)
def index(request):
    post_list = Post.objects.all()
    page_obj, page_number = paginator_create(request, post_list)
    context = {
        'page_obj': page_obj,
        'page_index': page_number,
        'index': True
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts_profile = author.posts.all()
    page_obj, page_number = paginator_create(request, posts_profile)
    following = False
    res = posts_profile.filter(author__following__user=author)
    if not res.exists():
        following = True

    context = {
        'page_obj': page_obj,
        'page_number': page_number,
        'author': author,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm()
    comments = Comment.objects.filter(post=post_id)
    return render(request, 'posts/post_detail.html', {"post": post,
                                                      "form": comment_form,
                                                      "comments": comments})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts_groups = group.posts.all()
    page_obj, _ = paginator_create(request, posts_groups)
    context = {
        'page_obj': page_obj,
        'group': group

    }
    return render(request, "posts/group_list.html", context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/post_create.html',
                      {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('main:profile', post.author)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('main:post_detail', post_id=post_id)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('main:post_detail', post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('main:post_detail', post_id)
    context = {'form': form,
               'is_edit': True,
               'post_id': post_id}
    return render(request, 'posts/post_create.html', context)


@login_required
def follow_index(request):
    cur_user = get_object_or_404(User, id=request.user.id)
    post_list = (
        Post.objects.filter(author__following__user=request.user)
        .select_related('group')
    )
    page_obj, page_number = paginator_create(request, post_list)
    context = {
        'page_obj': page_obj,
        'page_index': page_number,
        'cur_user': cur_user,
        'follow': True
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    curr_user = request.user
    if request.user != author:
        follow_ex = author
        check_user_in_follow = (Follow.objects.filter(user=curr_user,
                                author=follow_ex.id))
        if not check_user_in_follow.exists():
            Follow.objects.create(user=curr_user, author=follow_ex)

    return redirect('main:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    curr_user = request.user
    if request.user != author:
        follow_ex = author
        check_user_in_follow = (Follow.objects.filter(user=curr_user,
                                author=follow_ex.id))
        if check_user_in_follow.exists():
            Follow.objects.filter(user=curr_user, author=follow_ex).delete()
    return redirect('main:profile', username)

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load addclass %}
{% block title %} Отслеживание всх интересующих постов {% endblock %}
{% block header %} Обновления по избранным авторам {% endblock %}
{% block content %}
    {% include 'posts/includes/switcher.html' %}

    {% for post in page_obj %}
            <div>
                Автор: 
                <a href="{% url 'main:profile' post.author.username %}">
                    {{ post.author.username|extra_addclass:"text-primary" }} 
                </a>
                <p>Дата публикации: {{ post.pub_date|date:"d M Y" }} </p>
            </div>
            <a class="btn btn-primary my-sm-0" href="{% url 'main:post_detail' post.pk %}">Читать</a>
            <p>{{ post.text|linebreaksbr }}</p>
            {% if post.group.slug %}
                Перейти на группу:
                <a href="{% url 'main:group' post.group.slug %}">
                    {{ post.group.title }}
                </a>
            {% endif %}
            <p>
                {% if user.is_authenticated %}
                    <div class="ml-2">
                        <a href="{% url 'main:post_edit' post.pk %}" class="btn btn-outline-primary my-2 my-sm-0" type="submit">Редактировать</a>
                    </div>
                {% endif %}
            </p>
                {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}

            {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load addclass %}
{% load thumbnail %}
{% block title %}{{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
    <div class="mt-4 text-center">
        <p>
            {{ group.description|linebreaksbr }}
        </p>
        {% for post in page_obj %}
            <h3>
                Ник-нейм: 
                <a href="{% url 'main:profile' post.author.username %}">
                {{ post.author.username|extra_addclass:"text-primary" }}
                </a> 
                <br/>
                Дата публикации: {{ post.pub_date|date:"d M Y" }}
            </h3>
            <p> {{ post.text|linebreaksbr }}
            </p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <hr>
        {% endfor %}
    </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load cache %}
{% load addclass %}
{% load thumbnail %}
{% block title %} Последние обновления на сайте {% endblock %}
{% block header %} Последние обновления на сайте {% endblock %}
{% block content %}
    {% include 'posts/includes/switcher.html' %}

        {% for post in page_obj %}
            <div>
                Автор: 
                <a href="{% url 'main:profile' post.author.username %}">
                    {{ post.author.username|extra_addclass:"text-primary" }} 
                </a>
                <p>Дата публикации: {{ post.pub_date|date:"d M Y" }} </p>
            </div>
            <a class="btn btn-primary my-sm-0" href="{% url 'main:post_detail' post.pk %}">Читать</a>
            <p>{{ post.text|linebreaksbr }}</p>
            {% if post.group.slug %}
            Перейти на группу:
            <a href="{% url 'main:group' post.group.slug %}">
                {{ post.group.title }}
            </a>
            {% endif %}
        
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p>
                {% if user.is_authenticated %}
                    <div class="ml-2">
                        <a href="{% url 'main:post_edit' post.pk %}" class="btn btn-outline-primary my-2 my-sm-0" type="submit">Редактировать</a>
                    </div>
                {% endif %}
            </p>
            {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}

            
        {% include 'posts/includes/paginator.html' %}
        
{% endblock %}

yatube/templates/posts/post_create.html
{% extends "base.html" %}
{% load addclass %}
{% block title %} 
    {{ is_edit|yesno:"Редактирования поста,Cоздания поста" }}
{% endblock %}
{% block header %}
    {{ is_edit|yesno:"Редактирования поста,Cоздания поста" }}
{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-body"> 
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}            
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form class="form my-3 p-3" 
                        action= "{% if is_edit %}{% url 'main:post_edit' post_id %}{% else %}{% url 'main:post_create' %}{% endif %}"
                        method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group row my-3 p-3">    
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>

                                <div>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                            {{ field.help_text|safe }}
                                        </small>
                                    {% endif %} 
                                </div> 
                            </div>
                        {% endfor %}
                        <input type="submit" value='{{ is_edit|yesno:"Редактировать, Создать" }}'>
                    </form>
                </div>  
            </div>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load addclass %}
{% load thumbnail %}
{% block title %}{{ post.test|truncatechars:15 }} {% endblock %}
{% block header %}{{ post.text|truncatechars:7 }}{% endblock %}
{% block content %}
  <article>
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }} | {{ post.author.username|extra_addclass:"text-primary" }}
        <a href="{% url 'main:profile' post.author.username %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if post.group.slug %}
      Перейти на группу:
      <a href="{% url 'main:group' post.group.slug %}">
         {{ post.group.title }}
      </a>
    {% endif %}

    <br>
    <a href="{% url 'main:post_detail' post.pk %}">подробная информация</a>
  </article>
  <article>
    {% if user.is_authenticated %}
        <div class="card my-4">
          <h5 class="card-header">Добавить комментарий:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'main:add_comment' post.id %}">
              {% csrf_token %} 
              <div class="form-group mb-2">
                <div class="fieldWrapper">
                  {{ form.text.errors }}
                  <label for="{{ form.text.id_for_label }}">Your message:</label>
                  {{ form.text }}
              </div>
              </div>
              <button type="submit" class="btn btn-primary">Отправить</button>
            </form>
          </div>
        </div>
    {% endif %}
  </article>
  {% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'main:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text }}
        </p>
      </div>
    </div>
{% endfor %} 


{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} Профиль {{ author.get_full_name }} {% endblock %}
{% block header %} Страница профиля {{ author.get_full_name }} {% endblock %}
{% block content %}

  {% for post in page_obj %}
    <h3>
      Автор: {{ post.author.get_full_name }} <br>
      Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    <div>
      {% if post.group.slug %}
        Группа <a href="{% url 'main:group' post.group.slug %}">
          {{ post.group.title }}
        </a>
      {% endif %}
    </div>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ author.posts.count }}</h3>
     
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'main:profile_unfollow' post.author.username  %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'main:profile_follow' post.author.username %}" role="button"
          >
            Подписаться
          </a>
      {% endif %}
     
    </div>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}


  {% include 'posts/includes/paginator.html' %}

{% endblock %} 